language: node_js
node_js:
  - 12
sudo: required
services:
    - docker

before_install:
    - docker build -t websample -f Dockerfile.dev .

scripts:
    - docker run websample yarn tesst -- --coverage