# base image
FROM node:12

# set working directory
WORKDIR /app

# RUN npm install react-scripts -g

# install and cache app dependencies
COPY package.json .
RUN yarn install
COPY . .
RUN git init

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# start app
CMD ["yarn", "start"]
